// GENERATED FILE — do not edit by hand.
// Produced by `npx tsx scripts/build-namepool.ts` from fl_namepool.csv.
// The world generator's name pool: 3-letter nat code → first/surname lists.

export interface GeneratedNamePool {
  first: string[];
  last: string[];
}

export const GENERATED_NAME_POOLS: Record<string, GeneratedNamePool> = {
  ALB: {
    first: ["Agim","Arben","Ardit","Armando","Bekim","Besnik","Blerim","Dritan","Elton","Endrit","Erjon","Ermal","Fatos","Genti","Gentian","Ilir","Jetmir","Kastriot","Klodian","Kreshnik","Leart","Ledion","Luan","Marash","Mentor","Nderim","Orges","Redon","Rezart","Shpend","Sokol","Taulant","Valon","Xhevdet","Ylli"],
    last: ["Bardhi","Berisha","Cani","Dervishi","Doda","Duro","Gashi","Gjoka","Hasani","Hoxha","Hyseni","Ismaili","Kelmendi","Kola","Krasniqi","Leka","Lika","Malaj","Meta","Muca","Nikolla","Osmani","Pasha","Prifti","Rama","Rexha","Sadiku","Selimi","Shala","Shehu","Tahiri","Ujkani","Vata","Xhaka","Zeneli"],
  },
  AND: {
    first: ["Aaron","Abel","Adrian","Aitor","Alberto","Alejandro","Alex","Alfonso","Alonso","Alvaro","Ander","Andres","Angel","Antonio","Bruno","Carlos","Cesar","Cristian","Daniel","David","Diego","Eduardo","Enrique","Esteban","Fabian","Fernando","Francisco","Gabriel","Gaizka","Gorka","Guillermo","Hector","Hugo","Iago","Ignacio","Iker","Ismael","Ivan","Jaime","Javier","Jesus","Joaquin","Jon","Jordi","Jorge","Jose","Juan","Julen","Julio","Leo","Lorenzo","Lucas","Luis","Manuel","Marco","Marcos","Mario","Martin","Mateo","Miguel","Nacho","Nicolas","Oscar","Pablo","Pedro","Raul","Ricardo","Rodrigo","Ruben","Salvador","Samuel","Santiago","Sergio","Tiago","Tomas","Unai","Valentin","Vicente","Victor","Xabier","Xavier","Yago","Yeray","Yoel"],
    last: ["Alonso","Alvarez","Araujo","Bautista","Blanco","Caballero","Campos","Carmona","Castro","Cruz","Cuesta","Delgado","Dominguez","Esteban","Fernandez","Franco","Garcia","Gil","Gonzalez","Guerrero","Gutierrez","Herrera","Iglesias","Jimenez","Lorenzo","Lozano","Martin","Martinez","Medina","Molina","Montero","Montes","Morales","Moreno","Navarro","Ortega","Ortiz","Pastor","Perez","Prieto","Ramirez","Ramos","Rodriguez","Rojas","Romero","Rubio","Ruiz","Salazar","Sanchez","Santana","Santos","Serrano","Suarez","Torres","Valverde","Vargas","Vega","Velasco","Vicente","Vidal","Vila","Zamora","Zaragoza"],
  },
  ARM: {
    first: ["Aram","Ararat","Arman","Armen","Artak","Artur","Ashot","Bagrat","Edgar","Eduard","Garik","Gevorg","Gor","Grigor","Hamlet","Hayk","Hrant","Ishkhan","Kamo","Karen","Levon","Manvel","Mher","Narek","Norayr","Rafael","Ruben","Samvel","Sargis","Sevak","Suren","Tatul","Tigran","Tiran","Vahan","Vahe","Vardan","Vazgen","Yervand","Zaven"],
    last: ["Arakelyan","Aslanyan","Avetisyan","Baghdasaryan","Balayan","Barseghyan","Danielyan","Davtyan","Galstyan","Gasparyan","Ghazaryan","Grigoryan","Hakobyan","Hambardzumyan","Harutyunyan","Hovhannisyan","Hovsepyan","Karapetyan","Khachatryan","Kirakosyan","Manukyan","Melkonyan","Minasyan","Mkrtchyan","Movsisyan","Muradyan","Nazaryan","Nersisyan","Ohanyan","Petrosyan","Poghosyan","Sahakyan","Sargsyan","Simonyan","Stepanyan","Tadevosyan","Torosyan","Vardanyan","Yeghiazaryan","Zakaryan"],
  },
  AUT: {
    first: ["Albert","Alexander","Andreas","Anton","Armin","Bernd","Bruno","Christian","Christoph","Daniel","Dieter","Dominik","Elias","Emil","Fabian","Felix","Florian","Fritz","Gerhard","Gregor","Hans","Harald","Herbert","Joachim","Jonas","Josef","Julian","Jurgen","Kilian","Klaus","Leon","Leonard","Luca","Manuel","Marco","Martin","Matthias","Max","Maximilian","Michael","Moritz","Oliver","Paul","Philipp"],
    last: ["Ackermann","Arnold","Bauer","Baumann","Berger","Braun","Bruckner","Brunner","Fischer","Geiger","Graf","Gross","Gruber","Haas","Herzog","Huber","Kaiser","Keller","Kraus","Lang","Maier","Mayer","Muller","Schmid","Schneider","Schubert","Vogel","Wagner","Weber","Weiss","Wolf","Zimmermann"],
  },
  AZE: {
    first: ["Aghabala","Anar","Bahlul","Ceyhun","Dashgin","Elmar","Elnur","Eltun","Elvin","Emin","Farid","Fuad","Gara","Hikmat","Ibrahim","Ilkin","Javid","Kamran","Kanan","Mahir","Mirsahib","Murad","Namig","Nijat","Nurlan","Orkhan","Rahman","Ramil","Ramin","Rashad","Sabuhi","Sahil","Samir","Tarlan","Tural","Turan","Ulvi","Vasif","Vugar"],
    last: ["Abbasov","Aghayev","Ahmadov","Aliyev","Amirov","Bagirov","Bayramov","Ceferov","Eyvazov","Farzaliyev","Garayev","Gasimov","Guliyev","Hasanov","Huseynov","Ibrahimov","Ismayilov","Jafarov","Khalilov","Mammadov","Mirzayev","Mustafayev","Nabiyev","Nasirov","Novruzov","Orujov","Panahov","Quliyev","Ramazanov","Rzayev","Sadigov","Safarov","Salahov","Shukurov","Tagiyev","Talibov","Valiyev","Veliyev","Yusifov","Zeynalov"],
  },
  BEL: {
    first: ["Aaron","Adam","Adrien","Alain","Alex","Alexandre","Andre","Anthony","Arthur","Baptiste","Ben","Benjamin","Benoit","Bjorn","Cedric","Charles","Clement","Damien","David","Dominique","Emmanuel","Eric","Fernand","Francois","Frederic","Frederik","Gerard","Gilles","Guillaume","Henri","Hugo","Jan","Jean","Jerome","Jonathan","Jordan","Julien","Kevin","Laurent","Loic","Louis","Lucas","Lucien","Ludovic","Marc","Mathias","Mathieu","Michel","Nicolas","Noah","Olivier","Pascal","Patrick"],
    last: ["Aubert","Benoit","Bernard","Bosman","Charles","Claus","Colin","Cornet","Courtois","Daems","De Bruyne","De Clercq","De Ridder","De Smet","Delacroix","Denis","Dubois","Dumont","Dupont","Fleury","Francois","Gerard","Hermans","Jacobs","Lambert","Lambertz","Laurent","Leclerc","Lefebvre","Legrand","Lemaire","Leroy","Martens","Nicolas","Noel","Olivier","Renard","Van Dooren","Van Loon","Van Roy","Van den Berg","Vermeulen"],
  },
  BIH: {
    first: ["Adnan","Almir","Amar","Anel","Armin","Asmir","Damir","Dino","Edin","Eldin","Elvir","Emir","Ermin","Faruk","Haris","Ismar","Jasmin","Kenan","Mersudin","Mirza","Muhamed","Nedim","Nermin","Nihad","Sanjin","Semir","Senad","Tarik","Vedad","Zlatan"],
    last: ["Ahmetovic","Bajramovic","Begic","Besic","Ceric","Dedic","Delic","Dzeko","Ferhatovic","Grbic","Hadzic","Halilovic","Hodzic","Ibisevic","Imamovic","Karic","Kolasinac","Lulic","Maric","Medunjanin","Memisevic","Mujic","Music","Osmanovic","Pjanic","Salihovic","Softic","Spahic","Suljic","Visca","Zukic"],
  },
  BLR: {
    first: ["Aleksandr","Aleksei","Alexei","Anatoly","Andrei","Anton","Artem","Bogdan","Boris","Denis","Dmitri","Dmitry","Eduard","Gennady","Gleb","Igor","Ilya","Ivan","Kirill","Konstantin","Leonid","Maksim","Mikhail","Nikita","Nikolai","Oleg","Pavel","Roman","Ruslan","Sergei","Stanislav","Valentin","Viktor","Vitali","Yaroslav","Yuri"],
    last: ["Andreev","Antonov","Bandarenka","Bykau","Charnyshou","Drazdou","Filipenka","Hancharou","Hrytsuk","Ivanov","Karpovich","Kavalenka","Kazlou","Kovalchuk","Kovalev","Kruk","Kuzniatsou","Lisitsa","Malinouski","Marozau","Melnik","Nesterenka","Novik","Pashkevich","Petrov","Piatrouski","Rabtsau","Sakalouski","Sauchanka","Statkevich","Tsimafeyeu","Vasilevich","Volkau","Yakubovich","Yarmolenka","Zhuk"],
  },
  BUL: {
    first: ["Aleksandar","Angel","Anton","Boris","Boyan","Bozhidar","Cyril","Denislav","Dimitar","Dragomir","Emil","Filip","Georgi","Ivan","Kaloyan","Krasimir","Kristian","Lubomir","Martin","Milan","Nikola","Nikolay","Petar","Plamen","Radoslav","Rumen","Stanislav","Stefan","Stoyan","Svetoslav","Todor","Tsvetan","Valeri","Vasil","Ventsislav","Yordan","Zhivko"],
    last: ["Angelov","Atanasov","Borislavov","Borisov","Dimitrov","Dobrev","Dragomirov","Georgiev","Grigorov","Hristov","Iliev","Ivanov","Kirilov","Kolev","Lazarov","Marinov","Mihaylov","Nedelchev","Nikolov","Pavlov","Petkov","Petrov","Radev","Simeonov","Stefanov","Stoyanov","Todorov","Tsvetanov","Vasilev","Yordanov","Zlatev"],
  },
  CRO: {
    first: ["Aleksandar","Ante","Boris","Borna","Bruno","Damir","Domagoj","Dragan","Duje","Filip","Fran","Goran","Hrvoje","Ivan","Ivica","Jakov","Josip","Josko","Karlo","Kristijan","Krunoslav","Lovro","Luka","Mario","Marko","Martin","Mate","Matej","Milan","Mislav","Nikola","Petar","Ratko","Sime","Stefan","Tomislav","Toni","Vedran","Vladimir","Zoran","Zvonimir"],
    last: ["Babic","Blazevic","Brozovic","Grgic","Gvardiol","Horvat","Ivanovic","Juric","Klaric","Knezevic","Kovac","Kovacevic","Kovacic","Lovren","Lovric","Maric","Markovic","Matic","Modric","Novak","Pavic","Pavlovic","Peric","Perisic","Petrovic","Popovic","Radic","Rakitic","Saric","Stanic","Tolic","Tomic","Vidovic","Vukovic","Zoric"],
  },
  CYP: {
    first: ["Achilleas","Alexandros","Anastasios","Andreas","Antonios","Apostolos","Aristeidis","Athanasios","Charalambos","Charalampos","Christakis","Christos","Dimitrios","Emmanouil","Evangelos","Fotios","Georgios","Grigoris","Ilias","Ioannis","Iraklis","Konstantinos","Kostas","Kyriakos","Lazaros","Lefteris","Leonidas","Loizos","Manolis","Marinos","Marios","Michail","Neophytos","Nikolaos","Odysseas","Orestis","Pambos","Panagiotis","Pavlos","Petros","Savvas","Sotirios","Sotiris","Spyridon","Stavros","Stefanos","Stelios","Tasos","Thanasis","Theodoros","Vangelis","Vasileios","Yannis","Yiannakis","Zisis"],
    last: ["Alexiou","Andreou","Angelopoulos","Antoniou","Athanasiou","Bakas","Charalambous","Chatzis","Christodoulou","Christofi","Diamantis","Dimitriou","Fotiadis","Galanis","Georgiou","Hadjigeorgiou","Ioannou","Karagiannis","Karalis","Katsaros","Konstantinou","Kyriakidis","Kyriakou","Lambrou","Liakos","Loizou","Makris","Manolas","Mavropoulos","Michael","Moraitis","Neophytou","Nikolaidis","Nikolaou","Oikonomou","Panagiotou","Papadakis","Papadopoulos","Papageorgiou","Papanikolaou","Pappas","Pavlou","Petridis","Raptis","Sakellariou","Samaras","Sideris","Solomou","Spyropoulos","Stavrou","Theodorou","Tzortzis","Vasileiou","Vlachos","Zafeiris"],
  },
  CZE: {
    first: ["Adam","Anton","Daniel","David","Dominik","Filip","Jakub","Jan","Jaroslav","Jiri","Josef","Karel","Ladislav","Libor","Lukas","Marek","Martin","Matej","Milan","Miloslav","Ondrej","Patrik","Pavel","Petr","Radek","Stepan","Vaclav","Vit","Vladislav","Vojtech","Zdenek"],
    last: ["Barta","Benes","Cerny","Dolezal","Dvorak","Fiala","Gruber","Hajek","Horak","Jelinek","Kolar","Kovac","Kral","Kucera","Marek","Navratil","Nemec","Novak","Novotny","Pokorny","Pospisil","Prochazka","Ruzicka","Sedlacek","Svoboda","Vesely","Vlcek","Zeman"],
  },
  DEN: {
    first: ["Adam","Adrian","Alexander","Anders","Andreas","Anton","Axel","Benjamin","Bent","Bjarne","Bjorn","Bo","Casper","Christian","Christoffer","Daniel","David","Emil","Erik","Filip","Halfdan","Harald","Henrik","Holger","Hugo","Jacob","Jan","Jens","Joachim","Johannes","Jonas","Kristian","Lars","Leif","Mads","Magnus","Martin","Mathias","Mikkel","Nicolai","Noah","Ole","Oliver","Peter","Rasmus","Rune","Simon","Stig","Sven","Thomas","Tobias","Torben","Victor","Viggo","William"],
    last: ["Andersen","Axelsen","Carlsen","Christensen","Clausen","Danielsen","Eriksen","Frandsen","Hansen","Henriksen","Holm","Holst","Jakobsen","Jensen","Jorgensen","Kristensen","Larsen","Lund","Mikkelsen","Moller","Nielsen","Nygaard","Olsen","Pedersen","Petersen","Rasmussen","Steensen","Svendsen","Thomassen","Thomsen","Winther"],
  },
  ENG: {
    first: ["Aaron","Adam","Aidan","Albert","Alexander","Alfie","Alfred","Andrew","Anthony","Archie","Arthur","Ashley","Barry","Benjamin","Billy","Blake","Bobby","Bradley","Brandon","Brian","Caleb","Cameron","Carl","Cedric","Charlie","Christian","Clive","Colin","Connor","Craig","Dale","Damian","Daniel","Darren","David","Dean","Dennis","Derek","Dominic","Dylan","Edgar","Edward","Edwin","Elliot","Ellis","Eric","Ethan","Finley","Finn","Fletcher","Frank","Freddie","Gary","George","Harold","Harry","Harvey","Isaac","Jack","Jacob","James","Jamie","Jamie-Lee","Joel","John","Jonah","Jordan","Joseph","Joshua","Julian","Karl","Kieran","Lee","Leon","Lewis","Logan","Louis","Luke","Marcus","Marvin","Matthew","Max","Michael","Nathan","Noah","Norman","Oliver","Oscar","Owen","Paul","Peter","Philip","Piers","Reece","Robin","Ryan","Samuel","Shaun","Simon","Spencer","Steven","Theo","Thomas","Toby","Tyler","Victor","Warren","William","Zachary"],
    last: ["Abbott","Adams","Ainsworth","Armstrong","Atkinson","Baker","Barlow","Barnes","Baxter","Bell","Bennett","Booth","Bradshaw","Brierley","Briggs","Brooks","Brown","Burton","Butler","Carr","Carter","Chambers","Chapman","Clark","Coles","Collins","Cook","Cooper","Cox","Cross","Dalton","Dawson","Dean","Dixon","Elliott","Ellis","Finch","Fisher","Fletcher","Ford","Foster","Fox","Gibson","Gray","Green","Hall","Harris","Hayes","Henderson","Hill","Holden","Holmes","Howarth","Jackson","Jarvis","Johnson","Jones","King","Knight","Lambert","Lewis","Long","Marshall","Mason","May","Moore","Morris","Newton","Nicholson","Noble","Osborne","Palmer","Parker","Phillips","Porter","Richardson","Sharp","Simpson","Smith","Taylor","Thomas","Turner","Walker","Webster","White","Williams","Wilson","Wright","Young"],
  },
  ESP: {
    first: ["Aaron","Abel","Adrian","Aitor","Alberto","Alejandro","Alex","Alfonso","Alonso","Alvaro","Ander","Andres","Angel","Antonio","Bruno","Carlos","Cesar","Cristian","Daniel","David","Diego","Eduardo","Enrique","Esteban","Fabian","Fernando","Francisco","Gabriel","Gaizka","Gorka","Guillermo","Hector","Hugo","Iago","Ignacio","Iker","Ismael","Ivan","Jaime","Javier","Jesus","Joaquin","Jon","Jordi","Jorge","Jose","Juan","Julen","Julio","Leo","Lorenzo","Lucas","Luis","Manuel","Marco","Marcos","Mario","Martin","Mateo","Miguel","Nacho","Nicolas","Oscar","Pablo","Pedro","Raul","Ricardo","Rodrigo","Ruben","Salvador","Samuel","Santiago","Sergio","Tiago","Tomas","Unai","Valentin","Vicente","Victor","Xabier","Xavier","Yago","Yeray","Yoel"],
    last: ["Alonso","Alvarez","Araujo","Bautista","Blanco","Caballero","Campos","Carmona","Castro","Cruz","Cuesta","Delgado","Dominguez","Esteban","Fernandez","Franco","Garcia","Gil","Gonzalez","Guerrero","Gutierrez","Herrera","Iglesias","Jimenez","Lorenzo","Lozano","Martin","Martinez","Medina","Molina","Montero","Montes","Morales","Moreno","Navarro","Ortega","Ortiz","Pastor","Perez","Prieto","Ramirez","Ramos","Rodriguez","Rojas","Romero","Rubio","Ruiz","Salazar","Sanchez","Santana","Santos","Serrano","Suarez","Torres","Valverde","Vargas","Vega","Velasco","Vicente","Vidal","Vila","Zamora","Zaragoza"],
  },
  EST: {
    first: ["Aleksander","Andres","Erik","Henri","Henrik","Indrek","Jaan","Joonas","Karl","Kaspar","Kevin","Kristjan","Margus","Marko","Mart","Marten","Martin","Mihkel","Priit","Ragnar","Rain","Rasmus","Raul","Rauno","Robert","Robin","Sander","Siim","Sten","Taavi","Tanel","Tarmo","Toomas","Urmas","Vallo","Vladislav"],
    last: ["Aas","Anton","Eller","Ilves","Kaasik","Kaljula","Karu","Kask","Kivi","Koppel","Kukk","Kuusk","Laur","Leht","Lepik","Lind","Luik","Magi","Mets","Nurk","Oja","Ots","Paju","Parn","Puusepp","Rand","Raudsepp","Rebane","Rohtla","Saar","Sarapuu","Sepp","Sild","Sillaste","Sults","Talts","Tamm","Tomson","Toom","Uibo","Vaher","Valge","Vares","Viks","Vill"],
  },
  FIN: {
    first: ["Aatos","Aleksi","Antti","Arttu","Eero","Eetu","Elias","Henri","Janne","Jari","Jarkko","Jere","Joonas","Juha","Jussi","Kari","Kasper","Lauri","Leevi","Matti","Miika","Mikko","Niko","Olli","Onni","Oskari","Pekka","Perttu","Petri","Rasmus","Riku","Roope","Sami","Samu","Santeri","Teemu","Timo","Toni","Topias","Tuomas","Urho","Valtteri","Veikko","Vesa","Ville"],
    last: ["Aaltonen","Ahonen","Halonen","Hamalainen","Heikkila","Heikkinen","Heinonen","Hiltunen","Immonen","Jarvinen","Jokinen","Kallio","Karjalainen","Kinnunen","Korhonen","Koskinen","Kuusela","Lahtinen","Laine","Laitinen","Lehtinen","Lehtonen","Leppanen","Makela","Makinen","Manninen","Mattila","Niemi","Nieminen","Ojala","Pesonen","Pukki","Rantanen","Rasanen","Saarinen","Salminen","Salo","Salonen","Savolainen","Sipila","Toivonen","Tuominen","Turunen","Vainio","Virtanen"],
  },
  FRA: {
    first: ["Adam","Adrien","Alain","Alex","Alexandre","Andre","Anthony","Arthur","Baptiste","Benjamin","Benoit","Cedric","Charles","Clement","Damien","David","Dominique","Edgar","Emmanuel","Eric","Florian","Francois","Frederic","Gabriel","Gerard","Gilles","Guillaume","Henri","Hugo","Jean","Jerome","Jonathan","Jordan","Julien","Kevin","Laurent","Loic","Louis","Lucas","Lucien","Ludovic","Marc","Marcel","Mathias","Mathieu","Michel","Nicolas","Noah","Olivier","Pascal","Patrick","Paul"],
    last: ["Adam","Albert","Aubert","Benoit","Bernard","Blanc","Charles","Colin","Cornet","Courtois","Delacroix","Denis","Dubois","Dumont","Dupont","Durand","Fabre","Faure","Fleury","Fournier","Francois","Garnier","Gerard","Girard","Grandjean","Lambert","Laurent","Leclerc","Lefebvre","Legrand","Lemaire","Leroy","Martin","Nicolas","Noel","Olivier","Renard","Simon"],
  },
  FRO: {
    first: ["Andrias","Bartal","Brandur","Egil","Eydun","Fridrik","Gunnleyg","Hallur","Hanus","Heini","Heri","Ivan","Jakup","Joannes","Jogvan","Kaj","Klaemint","Levi","Magnus","Mikkjal","Nicolai","Odmar","Oli","Palli","Petur","Poul","Rannvi","Rasmus","Rogvi","Sjurdur","Sofus","Sonni","Sverri","Teitur","Trondur"],
    last: ["Andreasen","Benjaminsen","Berg","Danielsen","Davidsen","Djurhuus","Edmundsson","Egilsson","Eliasen","Ellingsgaard","Frederiksen","Hansen","Hentze","Hoejgaard","Isaksen","Jarnskor","Jespersen","Joensen","Justinussen","Klettskard","Knudsen","Larsen","Mikkelsen","Mortensen","Nattestad","Nielsen","Olsen","Petersen","Rasmussen","Samuelsen","Skaale","Sorensen","Thomsen","Vatnhamar","Winther"],
  },
  GEO: {
    first: ["Aleksandre","Bachana","Badri","Beka","Davit","Elguja","Gia","Giorgi","Gocha","Guram","Ilia","Irakli","Jaba","Kakha","Lasha","Levan","Merab","Mikheil","Nika","Nikoloz","Otar","Paata","Saba","Shota","Temur","Tornike","Vakhtang","Valeri","Zurab","Zviad"],
    last: ["Arveladze","Beridze","Bolkvadze","Chakvetadze","Chanturia","Chkheidze","Devdariani","Dvalishvili","Gelashvili","Giorgadze","Gogia","Kapanadze","Kashia","Kharaishvili","Kobakhidze","Kvaratskhelia","Lobjanidze","Lomidze","Maisuradze","Mamardashvili","Melkadze","Nadiradze","Okriashvili","Qazaishvili","Shengelia","Tabatadze","Tsiklauri","Tsintsadze","Vashakidze","Zivzivadze"],
  },
  GER: {
    first: ["Aaron","Adam","Albert","Alex","Alexander","Andre","Andreas","Anton","Armin","Bastian","Ben","Benjamin","Bernd","Bjorn","Bruno","Christian","Christoph","Daniel","David","Dennis","Dieter","Dominik","Edgar","Elias","Emil","Eric","Erik","Fabian","Felix","Florian","Frank","Frederik","Fritz","Gabriel","Gerhard","Gregor","Hans","Harald","Henry","Herbert","Jan","Joachim","Jonas","Jonathan","Josef","Julian","Jurgen","Kevin","Kilian","Klaus","Lars","Leon","Leonard","Luca","Manuel","Marc","Marcel","Marco","Marcus","Martin","Mathias","Matthias","Max","Maximilian","Michael","Moritz","Niklas","Noah","Oliver","Pascal","Patrick","Paul","Philipp"],
    last: ["Ackermann","Adam","Albert","Arnold","Bauer","Baumann","Becker","Berger","Brandt","Braun","Breuer","Bruckner","Brunner","Claus","Eckert","Evers","Fischer","Frank","Frey","Friedrich","Geiger","Gerber","Graf","Gross","Gruber","Haas","Hartmann","Heinrich","Herzog","Hoffmann","Huber","Jacobs","Janssen","Kaiser","Keller","Klein","Koch","Kraus","Kruger","Lambertz","Lang","Maier","Martin","Mayer","Meier","Meyer","Muller","Neumann","Nowak","Peters","Pfeiffer","Richter","Roth","Schmid","Schmidt","Schneider","Schroder","Schubert","Schulz","Schumacher","Simon","Vogel","Wagner","Weber","Weiss","Werner","Winter","Wolf","Zimmermann"],
  },
  GIB: {
    first: ["Aaron","Abel","Adam","Adrian","Aidan","Aitor","Albert","Alberto","Alejandro","Alex","Alexander","Alfie","Alfonso","Alfred","Alonso","Alvaro","Ander","Andres","Andrew","Angel","Anthony","Antonio","Archie","Arthur","Ashley","Barry","Benjamin","Billy","Blake","Bobby","Bradley","Brandon","Brian","Bruno","Caleb","Cameron","Carl","Carlos","Cedric","Cesar","Charlie","Christian","Clive","Colin","Connor","Craig","Cristian","Dale","Damian","Daniel","Darren","David","Dean","Dennis","Derek","Diego","Dominic","Dylan","Edgar","Eduardo","Edward","Edwin","Elliot","Ellis","Enrique","Eric","Esteban","Ethan","Fabian","Fernando","Finley","Finn","Fletcher","Francisco","Frank","Freddie","Gabriel","Gaizka","Gary","George","Gorka","Guillermo","Harold","Harry","Harvey","Hector","Hugo","Iago","Ignacio","Iker","Isaac","Ismael","Ivan","Jack","Jacob","Jaime","James","Jamie","Jamie-Lee","Javier","Jesus","Joaquin","Joel","John","Jon","Jonah","Jordan","Jordi","Jorge","Jose","Joseph","Joshua","Juan","Julen","Julian","Julio","Karl","Kieran","Lee","Leo","Leon","Lewis","Logan","Lorenzo","Louis","Lucas","Luis","Luke","Manuel","Marco","Marcos","Marcus","Mario","Martin","Marvin","Mateo","Matthew","Max","Michael","Miguel","Nacho","Nathan","Nicolas","Noah","Norman","Oliver","Oscar","Owen","Pablo","Paul","Pedro","Peter","Philip","Piers","Raul","Reece","Ricardo","Robin","Rodrigo","Ruben","Ryan","Salvador","Samuel","Santiago","Sergio","Shaun","Simon","Spencer","Steven","Theo","Thomas","Tiago","Toby","Tomas","Tyler","Unai","Valentin","Vicente","Victor","Warren","William","Xabier","Xavier","Yago","Yeray","Yoel","Zachary"],
    last: ["Abbott","Adams","Ainsworth","Alonso","Alvarez","Araujo","Armstrong","Atkinson","Baker","Barlow","Barnes","Bautista","Baxter","Bell","Bennett","Blanco","Booth","Bradshaw","Brierley","Briggs","Brooks","Brown","Burton","Butler","Caballero","Campos","Carmona","Carr","Carter","Castro","Chambers","Chapman","Clark","Coles","Collins","Cook","Cooper","Cox","Cross","Cruz","Cuesta","Dalton","Dawson","Dean","Delgado","Dixon","Dominguez","Elliott","Ellis","Esteban","Fernandez","Finch","Fisher","Fletcher","Ford","Foster","Fox","Franco","Garcia","Gibson","Gil","Gonzalez","Gray","Green","Guerrero","Gutierrez","Hall","Harris","Hayes","Henderson","Herrera","Hill","Holden","Holmes","Howarth","Iglesias","Jackson","Jarvis","Jimenez","Johnson","Jones","King","Knight","Lambert","Lewis","Long","Lorenzo","Lozano","Marshall","Martin","Martinez","Mason","May","Medina","Molina","Montero","Montes","Moore","Morales","Moreno","Morris","Navarro","Newton","Nicholson","Noble","Ortega","Ortiz","Osborne","Palmer","Parker","Pastor","Perez","Phillips","Porter","Prieto","Ramirez","Ramos","Richardson","Rodriguez","Rojas","Romero","Rubio","Ruiz","Salazar","Sanchez","Santana","Santos","Serrano","Sharp","Simpson","Smith","Suarez","Taylor","Thomas","Torres","Turner","Valverde","Vargas","Vega","Velasco","Vicente","Vidal","Vila","Walker","Webster","White","Williams","Wilson","Wright","Young","Zamora","Zaragoza"],
  },
  GRE: {
    first: ["Achilleas","Alexandros","Anastasios","Antonios","Apostolos","Aristeidis","Athanasios","Charalampos","Christos","Dimitrios","Emmanouil","Evangelos","Fotios","Georgios","Grigoris","Ilias","Ioannis","Iraklis","Konstantinos","Kostas","Kyriakos","Lazaros","Lefteris","Leonidas","Manolis","Marios","Michail","Nikolaos","Odysseas","Orestis","Panagiotis","Pavlos","Petros","Savvas","Sotirios","Spyridon","Stavros","Stefanos","Tasos","Thanasis","Theodoros","Vangelis","Vasileios","Yannis","Zisis"],
    last: ["Alexiou","Angelopoulos","Antoniou","Athanasiou","Bakas","Chatzis","Christodoulou","Diamantis","Dimitriou","Fotiadis","Galanis","Georgiou","Ioannou","Karagiannis","Karalis","Katsaros","Konstantinou","Kyriakidis","Lambrou","Liakos","Makris","Manolas","Mavropoulos","Moraitis","Nikolaidis","Nikolaou","Oikonomou","Panagiotou","Papadakis","Papadopoulos","Papageorgiou","Papanikolaou","Pappas","Petridis","Raptis","Sakellariou","Samaras","Sideris","Spyropoulos","Stavrou","Theodorou","Tzortzis","Vasileiou","Vlachos","Zafeiris"],
  },
  HUN: {
    first: ["Adam","Adrian","Akos","Andras","Attila","Balazs","Barnabas","Bence","Csaba","Daniel","David","Dominik","Ferenc","Gabor","Gergely","Gergo","Henrik","Imre","Istvan","Janos","Karoly","Krisztian","Laszlo","Levente","Martin","Marton","Mate","Norbert","Peter","Roland","Stefan","Szabolcs","Tamas","Zoltan","Zsolt"],
    last: ["Balog","Balogh","Barta","Biro","Bogdan","Fabian","Farkas","Fekete","Fodor","Gal","Horvath","Juhasz","Kiss","Kovacs","Lakatos","Lukacs","Meszaros","Molnar","Nagy","Nemeth","Olah","Papp","Racz","Simon","Szabo","Szilagyi","Torok","Toth","Varga","Vincze"],
  },
  IRL: {
    first: ["Aidan","Barry","Brendan","Cathal","Cian","Ciaran","Colm","Conor","Cormac","Daithi","Dara","Darragh","Declan","Diarmuid","Donal","Eamon","Enda","Eoghan","Eoin","Fergal","Finbarr","Fionn","Gearoid","Kevin","Killian","Liam","Lorcan","Malachy","Micheal","Niall","Odhran","Oisin","Paddy","Padraig","Peadar","Ronan","Rory","Ruairi","Seamus","Sean","Senan","Shane","Tadhg","Turlough","Ultan"],
    last: ["Brennan","Burke","Byrne","Clarke","Coleman","Collins","Connolly","Cullen","Daly","Doyle","Duffy","Dunne","Egan","Farrell","Fitzgerald","Flynn","Gallagher","Hayes","Healy","Hogan","Hughes","Keane","Kelly","Kennedy","Lynch","Maguire","McCarthy","McLoughlin","Moore","Murphy","Murray","Nolan","O'Brien","O'Callaghan","O'Connell","O'Connor","O'Doherty","O'Donnell","O'Neill","O'Sullivan","Quinn","Reilly","Ryan","Sheridan","Walsh"],
  },
  ISL: {
    first: ["Alfred","Arnar","Arni","Aron","Asgeir","Baldur","Birgir","Birkir","Bjarni","Bjorn","Egill","Einar","Elvar","Fannar","Gardar","Gisli","Gudmundur","Gunnar","Gylfi","Halldor","Haukur","Hilmar","Hjalmar","Hordur","Ingi","Ivar","Johann","Jokull","Jon","Kari","Kjartan","Kolbeinn","Kristjan","Leifur","Logi","Magnus","Odin","Olafur","Orri","Oskar","Ragnar","Rurik","Sigurd","Sigurdur","Sindri","Snorri","Solvi","Sverrir","Thorsteinn","Tryggvi","Valur","Vidar","Viktor","Yngvi"],
    last: ["Arnason","Baldursson","Bjarnason","Einarsson","Eiriksson","Finnbogason","Fridriksson","Gislason","Gudjohnsen","Gudmundsson","Gunnarsson","Hafsteinsson","Hakonarson","Halldorsson","Hallgrimsson","Helgason","Ingason","Jokulsson","Jonsson","Karason","Karlsson","Kristjansson","Leifsson","Magnusson","Olafsson","Oskarsson","Palsson","Petursson","Ragnarsson","Sigurdsson","Sigurjonsson","Sindrason","Stefansson","Sveinsson","Thorsson","Thorsteinsson","Valsson"],
  },
  ISR: {
    first: ["Amit","Avi","Barak","Ben","Chen","Daniel","Dor","Ehud","Eli","Eran","Gal","Gilad","Guy","Hanan","Idan","Itamar","Itay","Lior","Liran","Maor","Moshe","Nadav","Nir","Noam","Ofir","Omri","Oren","Ori","Ran","Roi","Sagiv","Shay","Shon","Tal","Tomer","Yarden","Yehonatan","Yossi","Yuval","Ziv"],
    last: ["Amar","Ashkenazi","Avraham","Bar","Barda","Ben David","Biton","Cohen","Dahan","Dayan","Elbaz","Friedman","Gabay","Golan","Hadad","Harel","Kaplan","Katz","Kayal","Lavi","Levi","Malka","Menachem","Mizrahi","Natcho","Nissim","Ohana","Peretz","Refaelov","Segal","Shabtai","Sharon","Solomon","Tal","Turgeman","Vaknin","Weiss","Yosef","Zahavi","Zohar"],
  },
  ITA: {
    first: ["Alberto","Alessandro","Alessio","Andrea","Angelo","Antonio","Carmine","Claudio","Cristian","Daniele","Dario","Davide","Domenico","Edoardo","Emanuele","Enrico","Fabio","Federico","Filippo","Francesco","Gabriele","Giacomo","Gianluca","Giovanni","Giuseppe","Leonardo","Lorenzo","Luca","Manuel","Marco","Massimo","Matteo","Mattia","Michele","Nicola","Nicolo","Paolo","Pietro","Raffaele","Riccardo","Roberto","Rocco","Salvatore","Samuele","Sergio","Simone","Stefano","Tommaso","Valerio","Vincenzo"],
    last: ["Barbieri","Basile","Bianchi","Bruno","Caruso","Colombo","Conte","Conti","Coppola","Costa","De Luca","De Santis","Esposito","Farina","Ferrara","Ferrari","Ferretti","Fontana","Galli","Gallo","Gentile","Giordano","Grasso","Greco","Leone","Lombardi","Lombardo","Longo","Mancini","Marchetti","Mariani","Marino","Martini","Monti","Moretti","Palumbo","Parisi","Pellegrini","Ricci","Rinaldi","Rizzo","Romano","Rossi","Russo","Sanna","Santoro","Serra","Silvestri","Testa","Villa"],
  },
  KAZ: {
    first: ["Abzal","Aibek","Alibek","Almas","Askar","Azamat","Baglan","Bauyrzhan","Bekzat","Chingiz","Damir","Daniyar","Dias","Erbol","Farkhat","Galymzhan","Gani","Islambek","Kairat","Kanat","Madi","Maksat","Marat","Nurbek","Nurbol","Nursultan","Olzhas","Ruslan","Rustem","Sanzhar","Serik","Sultan","Talgat","Temirlan","Timur","Ulan","Yerbolat","Yerkebulan","Yerlan","Zhaslan"],
    last: ["Abdrakhmanov","Abilov","Akhmetov","Alimbekov","Amirov","Baimukhanov","Baitursynov","Bekbolatov","Bekmurat","Bekturov","Dauletov","Dosmagambetov","Esimov","Ibrayev","Iskakov","Kadyrbek","Kaliyev","Kenzhebek","Kuanyshbayev","Muratov","Nurgaliyev","Nurmagambetov","Nurpeisov","Omarov","Rakhimov","Sadykov","Sagatov","Sarsenov","Seitkali","Serikbayev","Sultanov","Suyumbayev","Tazhibayev","Toleutayev","Tulegenov","Yerlanov","Yesbolat","Zhaksybekov","Zhanabayev","Zhumabayev"],
  },
  KVX: {
    first: ["Agim","Arben","Arber","Ardit","Armando","Bardh","Bekim","Besnik","Blerim","Dritan","Driton","Elton","Endrit","Erjon","Ermal","Fatos","Fisnik","Genti","Gentian","Granit","Ilir","Jetmir","Kastriot","Klodian","Kreshnik","Labinot","Leart","Ledion","Luan","Marash","Mentor","Milot","Nderim","Orges","Redon","Rezart","Shpend","Shpetim","Sokol","Taulant","Valon","Veton","Xhevdet","Ylli","Zymer"],
    last: ["Ahmeti","Bardhi","Berisha","Bytyqi","Cani","Dervishi","Doda","Duro","Gashi","Gjoka","Halimi","Hasani","Hoti","Hoxha","Hyseni","Ismaili","Kastrati","Kelmendi","Kola","Krasniqi","Leka","Lika","Malaj","Meta","Morina","Muca","Muriqi","Nikolla","Osmani","Pasha","Prifti","Rama","Ramadani","Rexha","Rrahmani","Sadiku","Selimi","Shala","Shehu","Tahiri","Ujkani","Vata","Xhaka","Zeneli"],
  },
  LIE: {
    first: ["Adrien","Alain","Albert","Alexander","Alexandre","Andreas","Anthony","Anton","Armin","Baptiste","Benoit","Bernd","Bruno","Cedric","Christian","Christoph","Clement","Damien","Daniel","Dieter","Dominik","Dominique","Elias","Emil","Fabian","Felix","Florian","Francois","Frederic","Fritz","Gabriel","Gerhard","Gilles","Gregor","Guillaume","Hans","Harald","Herbert","Hugo","Jean","Jerome","Joachim","Jonas","Josef","Julian","Julien","Jurgen","Kilian","Klaus","Laurent","Leon","Leonard","Loic","Luca","Manuel","Marcel","Marco","Martin","Mathieu","Matthias","Max","Maximilian","Michael","Michel","Moritz","Nicolas","Oliver","Olivier","Paul","Philipp"],
    last: ["Ackermann","Arnold","Aubert","Bauer","Baumann","Benoit","Berger","Bernard","Blanc","Braun","Bruckner","Brunner","Dubois","Dupont","Fischer","Frey","Geiger","Gerber","Girard","Graf","Grandjean","Gross","Gruber","Haas","Herzog","Huber","Kaiser","Keller","Kraus","Lang","Maier","Mayer","Meier","Muller","Roth","Schmid","Schneider","Schubert","Vogel","Wagner","Weber","Weiss","Wolf","Zimmermann"],
  },
  LTU: {
    first: ["Algirdas","Anton","Arnas","Arvydas","Darius","Deividas","Domantas","Donatas","Egidijus","Giedrius","Gintaras","Ivan","Jaroslav","Julius","Karolis","Kestutis","Linas","Mantas","Marius","Mark","Mindaugas","Nerijus","Paulius","Rimas","Rokas","Saulius","Tadas","Tomas","Vaidas","Vytautas","Zydrunas","Zygimantas"],
    last: ["Adomaitis","Balciunas","Baranauskas","Butkus","Cesnauskis","Grigas","Jankauskas","Juska","Katilius","Kavaliauskas","Kazlauskas","Lukosius","Mikalauskas","Navickas","Norkus","Paulauskas","Petrauskas","Pociunas","Ramanauskas","Rimkus","Sakalauskas","Simkus","Stankevicius","Tamosaitis","Urbonas","Valantas","Vasiliauskas","Zemaitis","Zilinskas","Zukauskas"],
  },
  LUX: {
    first: ["Arthur","Aurelien","Ben","Charel","Charles","Christophe","Danel","Dylan","Enes","Fernand","Florian","Gilles","Henri","Jeff","Julien","Kevin","Laurent","Leandro","Louis","Lucien","Marvin","Mathias","Maxime","Mica","Nicolas","Olivier","Pit","Romain","Sebastien","Timothe","Tom","Tun","Vincent","Yannick"],
    last: ["Bernard","Bohnert","Braun","Da Silva","Deville","Diederich","Feltes","Ferreira","Frisch","Gengler","Gerson","Hemmen","Hoffmann","Jans","Kayser","Kirsch","Konsbruck","Kremer","Lentz","Majerus","Martins","Meyers","Nilles","Origer","Pereira","Petry","Reding","Reuter","Rodrigues","Schaus","Schmit","Schroeder","Simon","Steichen","Thill","Turpel","Wagner","Weis","Wilmes","Zenner"],
  },
  LVA: {
    first: ["Aigars","Aivars","Andris","Anton","Artis","Boris","Dainis","Edgars","Eduard","Einars","Gatis","Igor","Ivan","Ivars","Janis","Jaroslav","Karlis","Kaspars","Kristaps","Lauris","Maris","Mark","Martins","Normunds","Oskars","Raimonds","Renars","Rihards","Ritvars","Roberts","Uldis","Valters"],
    last: ["Auzins","Balodis","Berzins","Briedis","Cirulis","Dumins","Eglitis","Grinbergs","Jansons","Kalejs","Kalnins","Karklins","Krumins","Lacis","Liepins","Melnis","Neimanis","Osis","Ozolins","Ozols","Petersons","Priede","Rozitis","Skujins","Straume","Tomsons","Upitis","Vanags","Vitols","Zarins","Zvirgzdins"],
  },
  MDA: {
    first: ["Adam","Adrian","Alexandru","Alin","Anatolie","Andrei","Artur","Attila","Bogdan","Catalin","Ciprian","Claudiu","Constantin","Corneliu","Cosmin","Cristian","Daniel","Denis","Dragos","Dumitru","Emil","Eugeniu","Florin","Gabriel","Ghenadie","Grigore","Ion","Ionut","Iurie","Marin","Marius","Maxim","Mihai","Nichita","Nicolae","Nicu","Octavian","Oleg","Petru","Rares","Razvan","Sandu","Serghei","Sergiu","Sorin","Stefan","Tudor","Vadim","Valentin","Valeriu","Vasile","Veaceslav","Vitalie","Vlad"],
    last: ["Balan","Balogu","Barbu","Bejenaru","Biro","Botnari","Caraman","Cazac","Cebotari","Ciobanu","Cojocaru","Constantin","Craciun","Damascan","Dragomir","Dumitru","Gheorghe","Grosu","Gutu","Iliescu","Ionescu","Ionita","Iorga","Lupu","Marin","Matei","Munteanu","Nedelcu","Negru","Nistor","Oprea","Pop","Popa","Popescu","Postica","Racu","Radu","Radulescu","Rusu","Sandu","Serban","Sirbu","Spataru","Stan","Stancu","Stoica","Toma","Tudor","Ursu","Vasile","Voicu","Vremea","Zaharia"],
  },
  MKD: {
    first: ["Aco","Aleksandar","Angel","Anton","Blagoja","Boban","Bojan","Borce","Boris","Boyan","Bozhidar","Cyril","Darko","Dejan","Denislav","Dimitar","Dragomir","Emil","Filip","Georgi","Gjorgji","Ile","Ilija","Ivan","Jovan","Kaloyan","Kire","Krasimir","Kristian","Kristijan","Ljupco","Lubomir","Martin","Milan","Mite","Naum","Nikola","Nikolay","Pande","Petar","Petre","Plamen","Radoslav","Risto","Rumen","Sasko","Slave","Stanislav","Stefan","Stole","Stoyan","Svetoslav","Todor","Tome","Toni","Trajko","Tsvetan","Valeri","Vane","Vasil","Vasko","Ventsislav","Vlatko","Yordan","Zhivko","Zlatko"],
    last: ["Angelov","Angelovski","Atanasov","Bogdanovski","Borislavov","Borisov","Dimitrievski","Dimitrov","Dobrev","Dragomirov","Georgiev","Georgievski","Gjorgjievski","Grigorov","Hristov","Iliev","Ivanov","Ivanovski","Jovanovski","Kirilov","Kolev","Kostovski","Lazarevski","Lazarov","Marinov","Markovski","Micevski","Mihaylov","Mitrevski","Naumovski","Nedelchev","Nikolov","Nikolovski","Ognenovski","Pandev","Pavlov","Petkov","Petrov","Petrovski","Radev","Ristovski","Sekulovski","Simeonov","Simonovski","Spasovski","Stefanov","Stojanovski","Stoyanov","Tasevski","Todorov","Todorovski","Trajkovski","Tsvetanov","Vasilev","Vasilevski","Velkovski","Yordanov","Zafirovski","Zdravkovski","Zlatev"],
  },
  MLT: {
    first: ["Adam","Andre","Bjorn","Brandon","Cain","Clayton","Dean","Denni","Duncan","Edward","Ethan","Ferdinando","Gareth","Jake","Jodi","Joseph","Jurgen","Karl","Kurt","Luca","Luke","Malcolm","Matthew","Myles","Neil","Nicky","Nikolai","Owen","Rennie","Renzo","Rowen","Sammy","Shaun","Steve","Terence","Tristan","Vince","Wayne","Zach"],
    last: ["Abela","Agius","Attard","Azzopardi","Bartolo","Bezzina","Bonello","Borg","Briffa","Bugeja","Buttigieg","Cachia","Calleja","Camilleri","Caruana","Cassar","Cauchi","Cutajar","Dalli","Debono","Ellul","Falzon","Farrugia","Fenech","Galea","Gatt","Gauci","Grech","Magro","Micallef","Mifsud","Muscat","Pace","Portelli","Sammut","Schembri","Spiteri","Vella","Xuereb","Zammit"],
  },
  MNE: {
    first: ["Aleksa","Aleksandar","Andrej","Andrija","Balsa","Blazo","Bojan","Boris","Bozidar","Branislav","Danilo","Darko","Dejan","Dorde","Dragan","Dragoljub","Dragoslav","Dusan","Filip","Goran","Ivan","Janko","Krsto","Lazar","Luka","Marko","Milan","Milos","Miodrag","Mirko","Miroslav","Nebojsa","Nemanja","Nenad","Nikola","Novak","Ognjen","Petar","Predrag","Radomir","Radovan","Ranko","Risto","Sasa","Savo","Slobodan","Srdjan","Stefan","Strahinja","Uros","Vasilije","Velimir","Veljko","Veselin","Vladimir","Vojislav","Vukan","Vukasin","Zarko","Zeljko","Zoran"],
    last: ["Babic","Blagojevic","Boskovic","Bozovic","Djokovic","Djordjevic","Djukanovic","Djurisic","Ilic","Ivanovic","Jovanovic","Jovetic","Kaludjerovic","Knezevic","Kostic","Kovacevic","Krstic","Lakic","Lazic","Lukic","Markovic","Marusic","Mijatovic","Milic","Milosevic","Milovanovic","Mitrovic","Nikcevic","Nikolic","Novakovic","Obradovic","Pavlovic","Pejovic","Peric","Perovic","Petrovic","Popovic","Radovanovic","Radovic","Radulovic","Raicevic","Rakic","Ristic","Savic","Savicevic","Scekic","Scepanovic","Sekulic","Simic","Stankovic","Stojanovic","Tadic","Todorovic","Tomasevic","Vasic","Vucinic","Vujacic","Vukcevic","Vukovic","Zaric","Zivkovic"],
  },
  NED: {
    first: ["Aaron","Bart","Bas","Ben","Bjorn","Bram","Cas","Daan","Dennis","Dirk","Erik","Frank","Frederik","Gijs","Hendrik","Jan","Jasper","Jeroen","Jesse","Joost","Jorrit","Koen","Lars","Levi","Lucas","Maarten","Mees","Niels","Pieter","Rens","Rick","Ruben","Sem","Stijn","Sven","Teun","Thijs","Willem","Wouter"],
    last: ["Bakker","Blom","Boer","Bos","Bosman","Brouwer","De Boer","De Bruijn","De Graaf","De Groot","De Jong","De Vries","De Wit","Dekker","Dijkstra","Evers","Hendriks","Hermans","Jacobs","Janssen","Jonker","Kok","Lamers","Martens","Meijer","Mulder","Peeters","Peters","Smit","Van Dam","Van Dijk","Van Houten","Van Leeuwen","Van Loon","Van Vliet","Van den Berg","Van der Meer","Van der Velde","Van der Ven","Verbeek","Vermeulen","Visser","Vos","Winter"],
  },
  NIR: {
    first: ["Aaron","Aidan","Alan","Andrew","Bradley","Brian","Chris","Ciaran","Ciaron","Colm","Connor","Conor","Corry","Craig","Daniel","Declan","Dion","Gareth","Gavin","Hugh","Jamie","Jonny","Keith","Kieran","Kyle","Michael","Neil","Niall","Paddy","Patrick","Paul","Rory","Ross","Ryan","Sammy","Sean","Shaun","Shea","Steven","Stuart","Terry","Trai"],
    last: ["Boyce","Boyle","Bradley","Cathcart","Collins","Craig","Cunningham","Dallas","Doherty","Doyle","Dunn","Evans","Farrell","Ferguson","Graham","Hodson","Hunter","Johnston","Jones","Kearns","Kelly","Lafferty","Lavery","Lynch","Magennis","McAuley","McBride","McCann","McGinn","McGovern","McLaughlin","McNair","Mulgrew","Murphy","Norwood","Paterson","Quinn","Reid","Saville","Washington","Whyte"],
  },
  NOR: {
    first: ["Adam","Aleksander","Alexander","Andreas","Anton","Benjamin","Birger","Bjarne","Bjorn","Christian","Daniel","David","Elias","Erik","Eskil","Filip","Fredrik","Frode","Gunnar","Halfdan","Hallvard","Harald","Henrik","Ivar","Jakob","Jan","Johannes","John","Jon","Jonas","Kristian","Kristoffer","Lars","Leif","Magnus","Martin","Mathias","Nils","Noah","Odd","Odin","Ola","Ole","Oliver","Per","Peter","Rune","Sigurd","Simon","Sondre","Stig","Sven","Thomas","Tobias","Tor","Tore","Trygve","Viktor","William","Yngve"],
    last: ["Andersen","Andreassen","Bakke","Berg","Bjerke","Bjornsen","Carlsen","Christiansen","Dahl","Danielsen","Eliassen","Eriksen","Fredriksen","Hansen","Haug","Haugen","Henriksen","Jakobsen","Johannesen","Johnsen","Kristiansen","Larsen","Moen","Nygaard","Olsen","Pedersen","Ringstad","Ruud","Sandvik","Sivertsen","Solberg","Strom","Svendsen","Thomassen","Torgersen","Valberg","Vik"],
  },
  POL: {
    first: ["Adam","Adrian","Aleksander","Andrzej","Antoni","Arkadiusz","Artur","Bartosz","Bogdan","Cezary","Damian","Daniel","Dariusz","Dawid","Dominik","Filip","Grzegorz","Hubert","Igor","Jacek","Jakub","Jan","Janusz","Jerzy","Joachim","Kacper","Kamil","Karol","Konrad","Krzysztof","Leszek","Lukasz","Maciej","Maksymilian","Marcin","Marek","Mateusz","Michal","Mikolaj","Patryk","Pawel","Piotr","Przemyslaw","Rafal","Robert","Sebastian","Slawomir","Tomasz","Wiktor","Wojciech"],
    last: ["Adamczyk","Baran","Bialek","Borkowski","Chmielewski","Czarnecki","Dabrowski","Duda","Dudek","Gorski","Grabowski","Jablonski","Jankowski","Kaczmarczyk","Kaczmarek","Kalinowski","Kaminski","Kowalczyk","Kowalski","Kozlowski","Krawczyk","Krol","Kubiak","Kucharski","Lewandowski","Lis","Majewski","Malinowski","Mazurek","Michalski","Nowak","Nowakowski","Pawlak","Piotrowski","Rutkowski","Sikora","Sobczak","Sokolowski","Szulc","Szymanski","Tomaszewski","Urbanski","Wasilewski","Wisniewski","Wlodarczyk","Wojciechowski","Wojcik","Wrobel","Zajac","Zielinski"],
  },
  POR: {
    first: ["Abel","Adrian","Afonso","Alex","Antonio","Bernardo","Bruno","Carlos","Cristiano","Daniel","David","Diogo","Domingos","Duarte","Eduardo","Fernando","Francisco","Gabriel","Goncalo","Henrique","Hugo","Joao","Jorge","Jose","Leandro","Leo","Lucas","Luis","Manuel","Marco","Martin","Miguel","Nicolas","Nuno","Paulo","Pedro","Renato","Ricardo","Rodrigo","Ruben","Rui","Samuel","Telmo","Tiago","Tomas","Vasco","Vitor","Xavier","Ze"],
    last: ["Almeida","Araujo","Barbosa","Braga","Campos","Cardoso","Carvalho","Castro","Correia","Costa","Cruz","Dias","Duarte","Esteves","Fernandes","Ferreira","Fonseca","Gomes","Goncalves","Henriques","Lopes","Marques","Mendes","Neto","Nogueira","Nunes","Oliveira","Pacheco","Pereira","Pinto","Ramos","Reis","Ribeiro","Rocha","Rodrigues","Sa","Santana","Santos","Silva","Sousa","Teixeira","Vaz","Ventura","Vieira","Xavier"],
  },
  ROU: {
    first: ["Adam","Adrian","Alexandru","Alin","Andrei","Attila","Bogdan","Catalin","Ciprian","Claudiu","Cosmin","Cristian","Daniel","Denis","Dragos","Emil","Florin","Gabriel","Ionut","Marius","Mihai","Nicolae","Octavian","Rares","Razvan","Sorin","Stefan","Valentin","Vlad"],
    last: ["Balogu","Barbu","Biro","Ciobanu","Constantin","Dragomir","Dumitru","Gheorghe","Iliescu","Ionescu","Marin","Matei","Munteanu","Nedelcu","Nistor","Oprea","Pop","Popa","Popescu","Radu","Radulescu","Rusu","Sandu","Serban","Stan","Stancu","Stoica","Toma","Tudor","Vasile","Voicu","Zaharia"],
  },
  RUS: {
    first: ["Aleksandr","Aleksei","Alexei","Alexey","Anatoly","Andrei","Anton","Arsen","Artem","Artyom","Boris","Daniil","Denis","Dmitriy","Dmitry","Eduard","Egor","Evgeni","Evgeniy","Gennady","Georgi","Gleb","Grigory","Igor","Ilya","Ivan","Kirill","Konstantin","Leonid","Lev","Maksim","Mark","Matvey","Mikhail","Nikita","Nikolai","Oleg","Pavel","Pyotr","Roman","Rostislav","Ruslan","Semyon","Sergei","Stanislav","Stepan","Timofey","Timur","Valentin","Valeriy","Vasili","Veniamin","Viktor","Vitaliy","Vladimir","Vyacheslav","Yaroslav","Yuri","Zakhar"],
    last: ["Alekseyev","Andreev","Antonov","Artemyev","Avdeyev","Baranov","Belov","Belyayev","Bobrov","Bogdanov","Borodin","Bykov","Chernov","Chernyshov","Danilov","Davydov","Denisov","Dmitriyev","Dobrovolsky","Dorofeyev","Dubov","Egorov","Ermakov","Fedorov","Filatov","Filippov","Gerasimov","Golovin","Gorbunov","Grigoryev","Gromov","Gusev","Ignatyev","Ilyin","Ivanov","Kalinin","Karpov","Kiselev","Klimov","Kolesnikov","Komarov","Korolev","Kovalev","Kozlov","Kudryavtsev","Kuzmin","Kuznetsov","Larin","Leonov","Litvinov","Lobanov","Makarov","Malyshev","Medvedev","Melnikov","Mironov","Morozov","Nazarov","Nekrasov","Nikitin","Novikov","Orlov","Osipov","Panov","Pavlov","Petrov","Polyakov","Popov","Prokhorov","Romanov","Rybakov","Safonov","Savin","Semyonov","Sergeyev","Sidorov","Smirnov","Sobolev","Sokolov","Solovyov","Sorokin","Stepanov","Tikhonov","Titov","Trofimov","Vasiliev","Vinogradov","Volkov","Vorobyov","Yakovlev","Zaitsev","Zakharov","Zhukov"],
  },
  SCO: {
    first: ["Adam","Aidan","Alexander","Alistair","Andrew","Angus","Archie","Billy","Bobby","Brian","Bruce","Callum","Cameron","Clyde","Colin","Connor","Craig","Daniel","David","Derek","Donald","Douglas","Eric","Euan","Ewan","Fergus","Finlay","Finley","Finn","Fraser","Gary","Gavin","Glen","Gordon","Graeme","Hamish","Hector","Hugh","Iain","Jack","James","Jamie","John","Jordan","Joseph","Keith","Kenneth","Lachlan","Lewis","Logan","Malcolm","Matthew","Michael","Neil","Norman","Paul","Peter","Robin","Ronald","Rory","Ross","Ryan","Samuel","Scott","Steven","William"],
    last: ["Anderson","Armstrong","Baxter","Beattie","Bell","Black","Boyle","Brown","Burns","Cairns","Campbell","Clark","Crawford","Cunningham","Davidson","Douglas","Drummond","Duncan","Dunn","Ferguson","Fleming","Fletcher","Forbes","Fraser","Gibson","Graham","Grant","Gray","Hamilton","Henderson","Hunter","Innes","Irving","Johnston","Kerr","Lawson","MacDonald","MacKenzie","Marshall","McGregor","McLean","Nicholson","Reid","Robertson","Russell","Scott","Sharp","Simpson","Sinclair","Smith","Stewart","Wallace","Wilson","Young"],
  },
  SRB: {
    first: ["Aleksa","Aleksandar","Andrej","Bojan","Boris","Branislav","Darko","Dejan","Dorde","Dragan","Dragoslav","Dusan","Filip","Goran","Ivan","Lazar","Luka","Marko","Milan","Milos","Miroslav","Nebojsa","Nemanja","Nenad","Nikola","Ognjen","Petar","Predrag","Radovan","Sasa","Slobodan","Srdjan","Stefan","Strahinja","Uros","Veljko","Vladimir","Vojislav","Vukasin","Zarko","Zeljko","Zoran"],
    last: ["Babic","Blagojevic","Djokovic","Djordjevic","Ilic","Ivanovic","Jovanovic","Knezevic","Kostic","Kovacevic","Krstic","Lazic","Lukic","Markovic","Milic","Milosevic","Milovanovic","Mitrovic","Nikolic","Novakovic","Obradovic","Pavlovic","Peric","Petrovic","Popovic","Radovanovic","Radovic","Rakic","Ristic","Savic","Simic","Stankovic","Stojanovic","Tadic","Todorovic","Vasic","Zivkovic"],
  },
  SUI: {
    first: ["Adrien","Alain","Albert","Alexander","Alexandre","Andreas","Anthony","Anton","Armin","Baptiste","Benoit","Bruno","Cedric","Christian","Christoph","Clement","Damien","Daniel","Dominik","Dominique","Elias","Fabian","Felix","Francois","Frederic","Gabriel","Gilles","Gregor","Guillaume","Hans","Hugo","Jean","Jerome","Jonas","Josef","Julian","Julien","Laurent","Leon","Loic","Luca","Manuel","Marcel","Marco","Martin","Mathieu","Matthias","Michael","Michel","Nicolas","Oliver","Olivier","Philipp"],
    last: ["Ackermann","Arnold","Aubert","Baumann","Benoit","Berger","Bernard","Blanc","Brunner","Dubois","Dupont","Fischer","Frey","Gerber","Girard","Graf","Grandjean","Haas","Herzog","Huber","Keller","Meier","Muller","Roth","Schmid","Schneider","Vogel","Weber","Weiss","Zimmermann"],
  },
  SVK: {
    first: ["Adam","Andrej","Dominik","Dusan","Erik","Ivan","Jakub","Jozef","Juraj","Ladislav","Lukas","Marek","Martin","Matej","Matus","Michal","Milan","Miroslav","Norbert","Ondrej","Patrik","Pavol","Peter","Radoslav","Rastislav","Richard","Robert","Roman","Samuel","Stanislav","Stefan","Tomas","Vladimir","Zdenko"],
    last: ["Balaz","Bartos","Benes","Cerny","Dubovsky","Gajdos","Horvath","Hruska","Hudak","Jancik","Kovac","Kovacik","Kral","Kucera","Lukac","Mihalik","Mikula","Molnar","Nagy","Novak","Novotny","Poliak","Simko","Stefanik","Toth","Urban","Valko","Varga","Zeman"],
  },
  SVN: {
    first: ["Aleksandar","Ales","Andrej","Blaz","Bojan","Bostjan","Denis","Domen","Erik","Filip","Gasper","Goran","Gregor","Ivan","Jaka","Janez","Jure","Klemen","Luka","Marko","Martin","Matej","Matic","Miha","Milan","Nejc","Nik","Nikola","Primoz","Rok","Sandi","Sasa","Tadej","Tilen","Uros","Ziga"],
    last: ["Bozic","Bregar","Cerne","Golob","Horvat","Hribar","Jerman","Kastelic","Kos","Kovac","Kovacic","Krajnc","Kranjc","Lah","Mlakar","Novak","Novakovic","Oblak","Potocnik","Rozman","Sever","Tomazic","Turk","Verbic","Vidmar","Zajc","Zorko","Zupan","Zupancic"],
  },
  SWE: {
    first: ["Adam","Adrian","Albin","Alfred","Anders","Andreas","Anton","Aron","Arvid","Axel","Benjamin","Birger","Bjorn","Bo","Carl","Christoffer","Daniel","David","Dennis","Elias","Emil","Erik","Eskil","Filip","Fredrik","Gunnar","Gustav","Henrik","Hjalmar","Hugo","Ivar","Jakob","Jan","Johan","John","Jonas","Kristoffer","Lars","Leif","Linus","Ludvig","Magnus","Marcus","Martin","Mats","Mikael","Niklas","Nils","Noah","Oliver","Oskar","Patrik","Per","Peter","Pontus","Rasmus","Robin","Roger","Simon","Stefan","Stellan","Stig","Sven","Thomas","Tobias","Tommy","Ulf","Victor","Viktor","William","Yngve"],
    last: ["Andersson","Berg","Berggren","Berglund","Bergqvist","Bergstrom","Bjork","Bjorklund","Dahl","Eklund","Engstrom","Gustafsson","Hallberg","Holm","Holmberg","Holmgren","Johansson","Jonasson","Jonsson","Karlsson","Larsson","Lind","Lindberg","Lindgren","Lindholm","Lindqvist","Lindstrom","Lund","Lundberg","Lundgren","Mattsson","Nilsson","Nordlund","Nordstrom","Nyberg","Nystrom","Olsson","Persson","Rosenberg","Salomonsson","Sandberg","Sjoberg","Skoglund","Stenberg","Strom","Sundberg","Svensson","Wahlberg","Wallin","Westberg"],
  },
  TUR: {
    first: ["Ahmet","Ali","Alper","Alperen","Arda","Atakan","Ayberk","Aykut","Baran","Baris","Batuhan","Berk","Berkay","Bugra","Burak","Caglar","Can","Cenk","Cihan","Deniz","Emir","Emre","Enes","Erdem","Eren","Fatih","Ferhat","Furkan","Gokhan","Hakan","Halil","Hasan","Ibrahim","Ilker","Ismail","Kaan","Kerem","Mehmet","Melih","Mert","Muhammet","Murat","Mustafa","Oguz","Onur","Orhan","Ozan","Serkan","Tolga","Yusuf"],
    last: ["Acar","Aksoy","Altintas","Arslan","Aslan","Aydin","Balikci","Bozkurt","Bulut","Cakir","Celik","Cetin","Demir","Demirel","Dogan","Durmaz","Erdem","Erdogan","Eren","Guler","Gunay","Gunes","Kaplan","Kara","Karaca","Karaman","Kaya","Kilic","Korkmaz","Kurt","Ozcan","Ozdemir","Ozturk","Polat","Sahin","Sari","Sezer","Simsek","Soylu","Tekin","Topal","Turan","Ucar","Uysal","Yavuz","Yildirim","Yildiz","Yilmaz","Yuksel","Zengin"],
  },
  UKR: {
    first: ["Anatoly","Andriy","Anton","Artem","Bogdan","Bohdan","Denis","Dmytro","Igor","Ivan","Leonid","Maksym","Mark","Mykhailo","Oleh","Oleksandr","Oleksii","Petro","Roman","Rostislav","Rostyslav","Ruslan","Sergei","Serhii","Stanislav","Stepan","Taras","Valentin","Valeriy","Vasyl","Viktor","Volodymyr","Yaroslav","Yevgen","Yevhen","Yevhenii","Yuri","Yuriy"],
    last: ["Bondar","Bondarenko","Boyko","Demyanenko","Dobrovolsky","Koval","Kovalchuk","Kovalenko","Kravchenko","Kravchuk","Lysenko","Malinovskyi","Marchenko","Melnyk","Moroz","Mudryk","Oliynyk","Petrenko","Polishchuk","Rudenko","Savchenko","Shevchenko","Shevchuk","Sydorchuk","Tarasenko","Tkachenko","Tkachuk","Yarmolenko","Yermolenko","Zinchenko"],
  },
  WAL: {
    first: ["Aaron","Adam","Aled","Arthur","Ashley","Barry","Benjamin","Bryn","Carwyn","Cerys","Craig","Dafydd","Daniel","Darren","David","Deiniol","Dylan","Eifion","Ellis","Emyr","Ethan","Gareth","Gary","Geraint","Gruffydd","Gwilym","Huw","Hywel","Iestyn","Ieuan","Iwan","Jack","Jacob","James","John","Jordan","Joshua","Lee","Llewellyn","Luke","Matthew","Meirion","Michael","Morgan","Nathan","Noah","Oliver","Owain","Owen","Reece","Rhodri","Rhys","Ryan","Samuel","Sion","Thomas","Tomos","Trystan","Wyn","Zachary"],
    last: ["Adams","Bevan","Davies","Edwards","Ellis","Evans","Griffiths","Harris","Hayes","Hughes","Jones","Lewis","Llewellyn","Lloyd","Meredith","Morgan","Morris","Owen","Phillips","Powell","Price","Prichard","Pugh","Rees","Roberts","Rowlands","Smith","Thomas","Tudor","Vaughan","Williams","Wynne"],
  },
};
